### ISSUE TITLE
[1.12.2] Can't place cart

### ISSUE THREAD

**Issue by microcontroling1** [modmuss50/SC2#102]
When placing cart, it just disappearing from inventory.
Tested with just Minecraft and RebornCore (3.4.11.153) Steve's carts (2.4.12.62)
Forge 14.23.0.2538

**Comment by modmuss50** [comment]
Is there anything in the log?

**Comment by microcontroling1** [comment]
https://gist.github.com/microcontroling1/71228a5c4a7262e0fed53be4aedc1cfe

**Comment by modmuss50** [comment]
Try using 14.23.0.2537 version of forge, as I think the newest forge has issues.

**Comment by microcontroling1** [comment]
Works with 2537. Thanks for fast response!
