### ISSUE TITLE
[1.12.2-2.4.13.69] array out of bounds exception

### ISSUE THREAD

**Issue by kreezxil** [modmuss50/SC2#107]
crashes dedicated server Forge 1.12.2 build 2581

crash report:
https://gist.github.com/ba01b7a5a73ba9ee5c6fc1a86061c6db

fml server latest:
https://gist.github.com/870763582401c7fb9674bea36db40a62

**Comment by GoryMoon** [comment]
Can't reproduce this, what modules did you have on the cart.

**Comment by kreezxil** [comment]
this is from so long ago, I can't possibly tell you. had you responded
earlier I could've told you what was there. sadly, you'll have to close
this.
