### ISSUE TITLE
[1.12.2] Chunkloader Module

### ISSUE THREAD

**Issue by vinicarra** [modmuss50/SC2#109]
I'm playing in my own dedicated server with my friends and we're trying to use a mining cart with the chunk loader module but it doesn't work, the chunks doesn't keep loaded when we leave the server.

- I'm not using any mods that adds chunkloaders but chickenchunks
- Chickenchunks works so there's nothing related to configs

**Comment by GoryMoon** [comment]
Think this is fixed, can you test this with 2.4.16
