### ISSUE TITLE
Crash when trying to shift-click items into the cart assembler

### ISSUE THREAD

**Issue by LWnellA** [modmuss50/SC2#11]
[crash-2016-11-11_21.49.10-client.txt](https://github.com/modmuss50/SC2/files/587237/crash-2016-11-11_21.49.10-client.txt)
[crash-2016-11-12_10.31.22-client.txt](https://github.com/modmuss50/SC2/files/587238/crash-2016-11-12_10.31.22-client.txt)
I had a few mods at the time, and the crashes stopped once I removed all mods.

**Comment by modmuss50** [comment]
Posting as gist: https://gist.github.com/modmuss50/2099234d5e5ee167f71d69401fc74f2b

And calling @mezz as it seems to be a JEI stacktrace.

**Comment by mezz** [comment]
This was fixed in a more recent version of JEI.
