### ISSUE TITLE
1.12 Error in client log - All players disconnected from server

### ISSUE THREAD

**Issue by VimbaTheFish** [modmuss50/SC2#111]
https://pastebin.com/Z69RG8VD - ftml-client-latest.log

spongeforge-1.12.2-2555-7.0.0-BETA-2797.jar
StevesCarts-1.12.2-2.4.13.69.jar

Players disconnect sometimes with message in client (Fatal error. Connection is terminated)

**Comment by modmuss50** [comment]
Can I have the server log at the time of the disconnect? As that log is only a warning and does not mean the user is disconnected.

**Comment by VimbaTheFish** [comment]
If that's only a warning, my problem just not connected with stevecarts. This message is only suspicious thing I found - server doesn't write anything at the moment of disconnect. So, I'll close the issue, sorry for wrong alarm.
