### ISSUE TITLE
[1.10.2] carts won't place 

### ISSUE THREAD

**Issue by tonimark** [modmuss50/SC2#118]
so I attempt to place down a miner cart with a drill and creative hull and it says that it failed to be placed in the world and post the log here:
[notes.txt](https://github.com/TechReborn/StevesCarts/files/1648884/notes.txt)
I seek the log and says that this cart is broken other trucks like woodcutter works normally cart won't placed and even above 64 height in case. if you ask if you tell me about remove foam fix I can't do it because the game won't longer initializing then in case of more information you can contract the modpack that I use:https://forum.resonantri.se/

**Comment by GoryMoon** [comment]
Update foamfix or set `B:fasterEntityDataManager=false` in the foamfix config.
