### ISSUE TITLE
Minecraft 1.10.2 Galactic Engineers mod pack

### ISSUE THREAD

**Issue by Cormenthor2** [modmuss50/SC2#119]
Built a mining cart, went to place it and get an error message stating it can not be placed because of an issue with 1 or more modules and to please post my log to the issue tracker here. So here it is.
[latest.log](https://github.com/TechReborn/StevesCarts/files/1657902/latest.log)

**Comment by GoryMoon** [comment]
Update foamfix or set `B:fasterEntityDataManager=false` in the foamfix config.
