### ISSUE TITLE
Cart modifier bug

### ISSUE THREAD

**Issue by lovelyjohn2002** [modmuss50/SC2#120]
If i get for example farmer to cart modifier, and in Assembler click to assemble, the farmer duplicates. It´s bug or i am doing something bad?

**Comment by GoryMoon** [comment]
This is a known issue, haven't taken the time to look at the upgrades closer yet

**Comment by lovelyjohn2002** [comment]
Ok thanks. Is there upcoming update? I have it on server, and do not wanna to players can duplicate harvesters :D

**Comment by GoryMoon** [comment]
Fixed in dev
