### ISSUE TITLE
i cant open my minecraft~~

### ISSUE THREAD

**Issue by bluetree01** [modmuss50/SC2#121]
i cant open my minecraft~~
it said"steves carts 2 is missing mods it depends on.
![default](https://user-images.githubusercontent.com/36141736/35784227-f7b1cc82-0a4f-11e8-82de-7e953cd5e9b6.PNG)

**Comment by GoryMoon** [comment]
You need reborncore to run it https://minecraft.curseforge.com/projects/reborncore
