### ISSUE TITLE
[1.12.2] Cart modifier yields cart and cart parts

### ISSUE THREAD

**Issue by smithy24** [modmuss50/SC2#124]
The modifier effectively doubles every modified cart.
The time it takes to modify a cart is higher than the assembly time (30 min for a small module).

**Comment by GoryMoon** [comment]
Haven't look at the time, but I'm guessing it's a balancing thing.
The modifying itself have been fixed in dev

**Comment by GoryMoon** [comment]
The modifier have been fixed in a release build and I don't notice that assembling takes longer when modifying a cart, it's always the cost of the hull and then it depends on added/removed modules
