### ISSUE TITLE
Suggestion: Linking Carts?

### ISSUE THREAD

**Issue by Akitori** [modmuss50/SC2#129]
Hiya! I want to make a working train using steve's carts! (you know, one lead engine while others follow behind it?)

Would it be possible to implement?

**Comment by GoryMoon** [comment]
This is not the purpose with this mod, it's ment to have it all in one.

What Vswe (the original creator of this mod) have said about a feature like this before
> The mod is designed so that you can put the features you would like into one cart, so it doesn't fit the mod design to link carts together. That on it's own is not a reason but it's a lot of work to code cart links.
