### ISSUE TITLE
(1.10.2) All the Mods Expert remastered. Cant place mining cart in world

### ISSUE THREAD

**Issue by Cnights** [modmuss50/SC2#131]
I built a cart for mining with the following modules.
Reinforced hull
Hardened drill
Torch Placer
Bridge builder
Railer
Liquid sensor
Height controller
chunkloader

I have tried all versions of foam fix per other issues. I even tried disabling foamfix and it still doesn't work. I haven't been able to locate the log for some reason. I am playing on a server so I cant do anything with mods that aren't client side. Thanks!

**Comment by GoryMoon** [comment]
Probably need to change on the server, not doing any updates to 1.10.2 anymore. Would need to find a fix yourself, sorry.
