### ISSUE TITLE
Track remover never turning off

### ISSUE THREAD

**Issue by Dustin1184** [modmuss50/SC2#136]
used to stop after passing by module toggler, past few versions it just picks up the advanced rail and keeps going. Kinda kills my auto mining :( using version 1.12.2-2.4.18.92

**Comment by mfsrf01** [comment]
I can confirm, i have the same issue.
Track remover doesn't stop picking up track at the Module Toggler.

**Comment by andythorntonjr** [comment]
Confirmed here as well. Using Modpack AllTheMods3 (1.12.2-2.4.18.92 version of Steve's Carts mod). Track Remover just passes right by the Module Toggler. Added an Advanced Detector Rail and nothing is stopping the Remover.

**Comment by auddie2015** [comment]
The drill is not stopping for me either. It could be the Module Toggler and not the Track Remover. The drill sucked my up signals. LOL

**Comment by MartinEggerstedt** [comment]
Ich can confirm this also. I have a chunk loader in the Cart with the track remover. That turns off but the remover goes on to remove the tracks
