### ISSUE TITLE
Drill Cart glitches into block

### ISSUE THREAD

**Issue by tbullock** [modmuss50/SC2#153]
Heyo,

I spent a bit of time playing with this mod today, saw some odd behavior that would stop mining carts from progressing.

The mining cart has a liquid sensor and a height controller set to 9 as well as railer.

The behavior i've seen is that the cart will spontaneously drop 1 height (to 8 in this case), place a rail and then move "into" the block infront of the cart.

https://i.imgur.com/yQl6IVU.png <-- see this image for an example.

I spent a few minutes looking for water or liquid blocks that might have impacted behavior but couldn't find any nearby.

I'm running the latest release on curseforge as of this post StevesCarts-1.12.2-2.4.21.107

Odd behaviour, looks like a bug to me. Thought i'd post it.

**Comment by DasIstVoltone** [comment]
Module "Bridge Builder" was installed on the cart?

**Comment by tbullock** [comment]
So yes the bridge builder module is installed, however I've restarted the client and have not been able to reproduce the behavior after several hours of allowing the cart to mine.

If I don't see the behavior repeat itself I guess I'll close the issue in the next day or so.
