### ISSUE TITLE
[1.7.10] Solar Engine

### ISSUE THREAD

**Issue by MrGrader** [modmuss50/SC2#154]
I don't know whether it is a bug or a feature, but solar engine in carts works if, say, Vibrant Quartz Glass is put above the rails. It basically works if there is any source of light apart from sun, and hence carts on solar engines work even during the night, which makes solar engine more like creative engine, since blocks that emit light are not that difficult to craft.

Tested on StevesCarts 2.0.0.b18, bug spotted on GT:NH.

**Comment by GoryMoon** [comment]
1.7.10 isn't supported anymore and this have been fixed in newer versions.
