### ISSUE TITLE
Cage module doesn't let me drop the mob.

### ISSUE THREAD

**Issue by Infernalboy95000** [modmuss50/SC2#157]
I tried in many ways to make the cage module to drop it's containing mob but I can't do it either manually (on it's GUI) or with the use of the module toggler.

I only can drop it by destroying the cart.
![2018-09-05_16 13 31](https://user-images.githubusercontent.com/39791183/45099077-c19d8680-b126-11e8-9884-1ada10ae8ac7.png)

![2018-09-05_16 15 03](https://user-images.githubusercontent.com/39791183/45099154-eeea3480-b126-11e8-8f22-571a9706e76a.png)

![2018-09-05_16 15 12](https://user-images.githubusercontent.com/39791183/45099163-f3aee880-b126-11e8-8eb6-c8f97895ee66.png)

Am I doing something wrong?

**Comment by EmbeddedTurtle** [comment]
I'm having the same problem.
