### ISSUE TITLE
Tree API uses outer class

### ISSUE THREAD

**Issue by Snownee** [modmuss50/SC2#158]
https://github.com/TechReborn/StevesCarts/blob/1.12/src/main/java/vswe/stevescarts/api/farms/ITreeModule.java#L8

**Comment by modmuss50** [comment]
Can you depend on the full jar for now? There shouldn't be a need to ship the api anymore. This isnt something that I see an easy way to fix without a large amount of work. In 1.13 we might expand the api and that would allow us to fix this.

**Comment by Snownee** [comment]
OK thanks.
