### ISSUE TITLE
External Distributor crashed.

### ISSUE THREAD

**Issue by sfchipan** [modmuss50/SC2#163]
Version: 1.12.2-2.4.23.115
Forge Version: 14.23.4.2749
The window pops up when I hold the External Distributor and press the shift right-click Liquid manager, but there is no crash report.
https://youtu.be/SwH8XPBkLho

**Comment by GoryMoon** [comment]
Can you send the `latest.log` or the log from when it crashed?
They are located in the `logs` folder in your instance.

**Comment by sfchipan** [comment]
[This is the latest.log.](https://www.dropbox.com/s/qqsu6uda24q386u/latest.log?dl=0)

**Comment by GoryMoon** [comment]
Did you run the world and made it crash and then uploaded the log?

**Comment by sfchipan** [comment]
OK, This is the log that just disconnected the server. https://www.dropbox.com/s/mvp5qick0u2ap7u/latest.log?dl=0

**Comment by GoryMoon** [comment]
Thank you, this log was helpful of what it issue is. I'm going to have a look at it some more and fix shortly.
As for now it's an incomparability with HoloInventory
