### ISSUE TITLE
Basic Wood Cutter chopping trees but not getting wood.

### ISSUE THREAD

**Issue by Column01** [modmuss50/SC2#167]
The basic wood cutter is cutting down the trees but it isn't getting any wood from it. It isn't going into the fuel, or any machines or anything. Just vanishing.

![java_2018-09-24_13-00-56](https://user-images.githubusercontent.com/26526649/45970569-e342ad00-c004-11e8-88e4-e9b769a4df2b.png)
![java_2018-09-24_13-00-59](https://user-images.githubusercontent.com/26526649/45970579-e8076100-c004-11e8-9c3f-9735bc6608b8.png)
 
The wood in the input is what I put inside.

**Comment by DrakusorU** [comment]
i'm having the same issue.. and this guy posted this in september, is this gonna be addressed? like tell us if there is a mod incompatability, why is this happenig.. in my session my wood cutter loses durability points but literally no wood gets cut..

**Comment by modmuss50** [comment]
Fixed with: https://github.com/TechReborn/StevesCarts/commit/2e42c2459e487c5f6557002f9ae82f6e6f6da60e
