### ISSUE TITLE
[2.4.25.121] Ticking enty - ClassCastException on join causing client crash

### ISSUE THREAD

**Issue by kreezxil** [modmuss50/SC2#170]
A player of mine has reported that they are crashing out to desktop when joining my server for my pack World of Dragons.

It appears to be a Ticking Entity issue caused by a ClassCastExcept in Modulechest.java at line 110.

His crash report: https://pastebin.com/E4D5Y5sC

**Comment by Protected** [comment]
Sounds similar to the problem I'm here to report so I'll just add it here.

https://pastebin.com/LWV72qfq is what I was given.

The effect is the same - Client-side crash on join.

**Comment by modmuss50** [comment]
Has this only started happening after updating the mod?
