### ISSUE TITLE
[1.12.2-2.4.26.125] woodcutter crashes client on dedicated server

### ISSUE THREAD

**Issue by kreezxil** [modmuss50/SC2#171]
One of my players keeps crashing out when enter a chunk possessing a woodcutter.

The exception is: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

Their crash report: https://pastebin.com/6LFyLZZe

**Comment by modmuss50** [comment]
humm, seems the same as #170 and I think its related to my change done here: https://github.com/TechReborn/StevesCarts/commit/0324a0036aa65ac25d48b4139db5da6d2dc8964f

Can you try with this version: https://github.com/TechReborn/StevesCarts/releases/tag/StevesCarts-1.12.2-2.4.23.113
if that fixes it I will revert my changes

**Comment by kreezxil** [comment]
ok, i'll load a test of my 40gb world and see if that fixes it.

**Comment by kreezxil** [comment]
@modmuss50 we did the test as you have requested and it worked flawlessly

**Comment by modmuss50** [comment]
Ok, thanks for testing. Its getting late here now, tomorrow I will revert the change (it doesnt change anything gameplay wise) and get a new version out.

**Comment by kreezxil** [comment]
excellent, I'll release an update of all my packs that has the buggy version stevescarts in it when i see the update. So definitely World of Dragons on that. The 5K downloads a week pack.
