### ISSUE TITLE
treetap module causing crash (local and server)

### ISSUE THREAD

**Issue by Piletz** [modmuss50/SC2#174]
Hi guys,
I got an issue with the treetap module, as soon as i layed my cart down, my server crashed and won't restart, on local it simply crash my minecraft.
here is the crash report :[crash-2018-12-28_14.58.28-server.txt](https://github.com/TechReborn/StevesCarts/files/2715072/crash-2018-12-28_14.58.28-server.txt)

**Comment by GoryMoon** [comment]
Update to `industrialcraft-2-2.8.99-ex112` or newer to fix this
