### ISSUE TITLE
[Suggestion] Holiday events toggle-able/always active

### ISSUE THREAD

**Issue by DWX12** [modmuss50/SC2#176]
I would like to see a config option to enable specific holiday events all the time. Sometimes people miss them and other times it's for testing or modpack purposes. Just a feature I'd like to see that other mods have.

A big thank you to everyone working and who has worked on this mod before.

**Comment by Yoghurt4C** [comment]
seconding this 🥈

**Comment by modmuss50** [comment]
done, thanks to @Yoghurt4C
