### ISSUE TITLE
[1.12.2] other mods are confused about stevescarts metablocks

### ISSUE THREAD

**Issue by Yoghurt4C** [modmuss50/SC2#178]
![image](https://user-images.githubusercontent.com/11313954/52507452-a0bfec80-2c02-11e9-9f01-8b62067a2987.png)
![image](https://user-images.githubusercontent.com/11313954/52507472-b1706280-2c02-11e9-8551-15be4328fe56.png)

**Comment by GoryMoon** [comment]
Block type don't need to match item metadata, it's remapped to the correct one before dropping/placing, there is no issue here.
