### ISSUE TITLE
[1.12.2]Hardened Wood Cutter doesn't plant saplings

### ISSUE THREAD

**Issue by jackraidenph** [modmuss50/SC2#189]
Setup: 
Reinforced Hull
Coal Engine
Compact Solar Engine
Advanced Smelter
Top Chest

The cart cuts down trees, but doesn't replant them having saplings in slot. Need to say, that blocks of dirt are floating in the air

**Comment by TheDeviantCrafter** [comment]
Make sure your cart has saplings in the wood cutter inventory. If your cargo manager is set to `all slots` it will take all of the saplings from that inventory, leaving it none to replant.

**Comment by jackraidenph** [comment]
I have already solved the problem. The problem was that cart plants saplings only on even block coords and my dirt blocks where on every uneven. I don't really remember as it was more than a month ago.
