### ISSUE TITLE
Advanced smelter not working 

### ISSUE THREAD

**Issue by leglerm** [modmuss50/SC2#19]
Hey there, 

like usual i installed 2 adv. smelters so one can output charcoal directly to engine and the other to the storage where i can both set a value for those two.

I cant change the output location (its on storage)
I cant change the amount (its on infinite)
Sometimes the recipe wood->charcoal disappears
He doesnt produce charcoal (i dont know when he made that one charcoal that he got)
There is a zero on the wood in the recipe

![2016-11-14_22 13 07](https://cloud.githubusercontent.com/assets/13408657/20283057/c5ece6ee-aab7-11e6-9bfe-35c548b8bbfb.png)

Btw: this is version 2.1.0.7 

On a sidenote on that version i also have the rending issue (no icon ingame for the cart) and a crash when placing 
[crash-2016-11-14_20.39.07-client.txt](https://github.com/modmuss50/SC2/files/590504/crash-2016-11-14_20.39.07-client.txt)

**Comment by modmuss50** [comment]
I think the icon issue _may_ have been fixed, the latest version is `2.1.0.39` so you are 32 versions behind. The furnace issue _may_ have been fixed in the newer issue with @Nedelosk fixing some things have may have been related.

So you could please update and get back to use.

**Comment by leglerm** [comment]
Did just upgrade to the newest version available. Smelter now working as expected. 

One minor thing is that sometimes the icons in the smelter recipe disappear when taking items out of the chest inventory. Simple closing the gui and reopen fixes this.
