### ISSUE TITLE
Santa resource breaks global servers

### ISSUE THREAD

**Issue by Routhinator** [modmuss50/SC2#192]
Server is in UTC, user is in PST. Any timezone that is behind UTC and has not passed midnight fails to connect because the santa resource is not loaded unless the client is booted on or after the 30th.

This resource should always be loaded.

```
16:38:16] [Client thread/ERROR] [FML]: Unidentified mapping from registry minecraft:villagerprofessions
[16:38:16] [Client thread/ERROR] [FML]:     stevescarts:santa: 11
[16:38:16] [Netty Epoll Client IO #0/ERROR] [FML]: Network Disconnect: Fatally missing registry entries
```

**Comment by Routhinator** [comment]
Setting the holidays to false and restarting the server and clients also fails to workaround this

**Comment by SomberDwarf** [comment]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@847dd5a1) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@d04e10e)

clients kicked with this message

**Comment by mcrewson** [comment]
Disabling the the christmas event in the mod's configuration, both server and client, does not solve this problem. 

However, changing the client computers clock to Nov 30, so it is on the same "local" date as the server, allows the client to login.

**Comment by modmuss50** [comment]
I didnt even know we had stanta things (or atleast I forgot).

**Comment by modmuss50** [comment]
released a new vesion that just stright up disables the easter eggs, If someone actaully wants to play with them please fix them via a PR.

**Comment by LaysDragon** [comment]
Shouldn't only register entity in holiday
It is toooooo easy to break the save file after the holiday if there is any easter egg entity in the world…
My server crash due to this implement of Easter egg,not big problem to deal,but I have to say it is  not a good way to make a easter egg in mods
:(

**Comment by Tulwean** [comment]
This mod has completely broken my server because of the holiday crap. Now that xmas is over my server is missing the registry for the Santa villager. I do /ftb confirm and my server hangs for 4 plus hours, creating a 100gig plus back up that exceeds my hosts storage space. I cant finished the back up so I cant launch my server.

**Comment by modmuss50** [comment]
Update the mod to prevent it happening again.

I wasnt aware that the easter eggs added registry entries, they NEVER should have done that.
