### ISSUE TITLE
FTB Revelation: Issues with Steve's Carts after Jan 1st

### ISSUE THREAD

**Issue by evelritual** [modmuss50/SC2#198]
Reposting [this issue](https://github.com/DarkPacks/SevTech-Ages/issues/4022) since it seems it's a Steve's Carts issue.

The following issue appears when joining a server around the new year:
```[18:31:04] [Server thread/WARN]: Forge Mod Loader detected missing registry entries.

There are 1 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:villagerprofessions:
    stevescarts:santa


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

Users are able to pass `-Dfml.queryResult=confirm` with mixed success. Ideally, since this flag confirms for *all* prompts across all mods, the solution would be to fix this mod-side so users can omit passing this.

More specific info in parent thread.

**Comment by Shivaess** [comment]
For the record we were unable to recover our world using this method and are attempting to recover from a backup.

**Comment by modmuss50** [comment]
This issue was fixed years ago. Sadly I wasn’t aware that this was contained in the mod so it should never of happened. (I only helped port it).

I see no reason why the worlds shouldn’t work after allowing the removed entries.
