### ISSUE TITLE
Incompatible with Industrial Craft 2

### ISSUE THREAD

**Issue by code32** [modmuss50/SC2#21]
After installing SC2 wires in Industrial Craft 2 stop working and displayed correctly. Energy ceases to be transferred through the wires. If the check was installed and other mods, perhaps it is not in Industrial Craft 2.

[Curse Profile](https://dl.dropboxusercontent.com/u/54210112/First-1.0.zip)

**Comment by modmuss50** [comment]
Wow, ok that is very weird.

**Comment by code32** [comment]
Sorry, the problem is not SC.
