### ISSUE TITLE
Crash when harvester interacts with beetroots

### ISSUE THREAD

**Issue by nightred** [modmuss50/SC2#22]
When a harvester interacts with a beetroot the server will crash.

https://gist.github.com/nightred/042a72a4b0067ee834ed250bfc5f8b30

**Comment by Prodiod** [comment]
Also got this crash. Server crash when a harvester tries to interact with the Pam's Harvest Craft peanut crops.  
[crash-2016-11-19_10.28.32-server.txt](https://github.com/modmuss50/SC2/files/601647/crash-2016-11-19_10.28.32-server.txt)
