### ISSUE TITLE
Cannot place cart

### ISSUE THREAD

**Issue by The-Scout** [modmuss50/SC2#23]
forge log http://www.mediafire.com/file/679ye60l24zw54u/fml-client-latest.log

If theres anything els you need just say this is the first issue i have ever reported.

**Comment by modmuss50** [comment]
Thanks for the report

**Comment by modmuss50** [comment]
What modules do you have on your cart?

**Comment by modmuss50** [comment]
Ok, ive uploaded a version that adds some extra debug info when a cart fails to place in the world. Mind testing with that version and sending me the logs again?

**Comment by The-Scout** [comment]
Sorry for late reply i had a pin and paper rpg to gm. http://www.mediafire.com/file/nsqrjgi31yv1kvp/latest.log

http://www.mediafire.com/file/679ye60l24zw54u/fml-client-latest.log

there.

**Comment by modmuss50** [comment]
Awesome thanks 👍 

Leaving this snippit of the log for tomorrow: https://gist.github.com/modmuss50/39e98d1c0f29b6fa84c8f357619c4832

**Comment by ccgfok** [comment]
This bug happened when creating modules steve's cart for the first time, then quit and re-join this saved world. Now I cant place saved module cart.
![2016-11-25_23 29 25](https://cloud.githubusercontent.com/assets/11695493/20640632/edb1d79a-b415-11e6-9a68-c32c8612faf0.png)

**Comment by modmuss50** [comment]
Can I have the log file please, there will be some extra information that I need in there.

**Comment by ccgfok** [comment]
here
https://github.com/ccgfok/as/blob/master/fml-client-latest.log

**Comment by modmuss50** [comment]
Great thanks, it seems to be the same issue as before.

Snippit off the log containing the info needed:
https://gist.github.com/modmuss50/470fd21c9ef69c35f6accabac035e6ae

@Nedelosk you might have to look into this as I have no idea how the data watchers work.

**Comment by ccgfok** [comment]
It happened on all modules, not only the modules that I post my logs file.

**Comment by modmuss50** [comment]
Humm, im not too sure whats up with this one, I will need to get @Nedelosk to look at it.

**Comment by modmuss50** [comment]
I need a way to constantly reproduce this, I have a feeling its another mod causing the issues. If someone can give me a mod pack and/or a world that they can constantly make this happen that would be a lot of use.
