### ISSUE TITLE
Basic tree farm sapling problem

### ISSUE THREAD

**Issue by benten2000** [modmuss50/SC2#26]
I have tried the latest SC2 on my large modded Minecraft as well as on its own to test but still get this weird problem.

Made a normal tree farm cart with solar engine, basic wood cutter, fertilizer and side chests.
The cart heads off and starts planting the oak saplings but after a few seconds the saplings pop out of the ground and hover there to be picked up.
Then if you right click the grass block the sapling was planted on it disappears so show another sapling planted underneath.

Same happens if you right click on a sapling that has been planted by the cart and it will show two (one of top of the other)

And lastly if a tree does grow before all other other saplings have been auto uprooted then they will all disappear and end up one block under the ground and the cart won't fertilize them or replant.

![2016-11-24_16 22 10](https://cloud.githubusercontent.com/assets/2871768/20605367/f73bdd06-b262-11e6-8376-c81b45048046.png)

**Comment by modmuss50** [comment]
Ok, do you have a fertiliser upgrade? I think its to do with that

**Comment by benten2000** [comment]
Yeah that was installed. I didn't think to try it without certain mods.
Shall give it a try now and test.

**Comment by modmuss50** [comment]
Im 90% sure thats the issue, I will look into it

**Comment by benten2000** [comment]
Great, thank you for the help and information.
