### ISSUE TITLE
JEI null recipe

### ISSUE THREAD

**Issue by Peach774** [modmuss50/SC2#29]
This mod is registering a recipe with a null itemstack which causes a nullpointer in JEI.

**Comment by modmuss50** [comment]
Ok thanks for letting me know, I have got a core mod I can run with this to try and track down the root of it

**Comment by modmuss50** [comment]
Fixed with https://github.com/modmuss50/SC2/commit/2afd680177ec44f54e360c7b1224d3c2a621cc01
