### ISSUE TITLE
Some Recipes are messed up or still missing (Upgrades not craftable and smeltery recipes messed up)

### ISSUE THREAD

**Issue by Garonne** [modmuss50/SC2#3]
Based on JEI "Reinforced Metal" and "Enhanced Galgadorian Metal" don't seem craftable in the current version of Steve's Carts. Or is there some "device" needed which is not displayed in JEI?

**Comment by Garonne** [comment]
Just figured out what went wrong. A lot of items return "Refined Handle" when being smelted... including "Large Lump of Galgador" (supposed to yield "Enhanced Galgadorian Metal" and "Stabilized Metal" (supposed to yield "Reinforced Metal")

**Comment by Garonne** [comment]
Upgrades don't have crafting recipes either yet.

Can provide MineTweaker/CraftTweaker script to fix those issues if wanted.

**Comment by FnordMan** [comment]
Yeah, looking at JEI it seems that everything in the mod smelts to a refined handle.

**Comment by modmuss50** [comment]
Humm that's strange, I will take a look.

**Comment by Garonne** [comment]
For people who want a quick hotfix like me:

This CraftTweaker script fixes the furnace recipes for Steve's Carts so at least that part is (temporarily) fixed. Extension needs to be changed back to .zs for it to work though.

[StevesCarts (Furnace Fix).zs.txt](https://github.com/modmuss50/SC2/files/586269/StevesCarts.Furnace.Fix.zs.txt)

**Comment by Nedelosk** [comment]
This issue is fixed with the last version.
