### ISSUE TITLE
Server Crash when placing bonemeal in fertilizer module slot

### ISSUE THREAD

**Issue by Cakestory** [modmuss50/SC2#31]
We are getting a server crash when placing bonemeal in the fertilizer slot in one of our Steve´s carts.
The crash seems to be caused my a deprecated method name in one of the latest 1.10.2 Forge versions.
I should mention that the crash happens every time the chunk with the cart is loaded on the server, because of it crashing in the "ticking entity" code, so it would be high priority for us to get it fixed. 

You can find the crash report here:
[crash-2016-12-15_13.32.47-server.txt](https://github.com/modmuss50/SC2/files/655528/crash-2016-12-15_13.32.47-server.txt)
or http://pastebin.com/pdfijC8e

Minecraft version: 1.10.2
Forge version: 12.18.2.2171
Steve´s Carts Reborn version: 2.1.0.59

If you need any further information feel free to ask. We are happy to help improving this mod.

**Comment by modmuss50** [comment]
Ok thanks for reporting this, I am busy for the next 48 hours so it will have to wait for a bit
