### ISSUE TITLE
Cart with solar module and woodcutter cannot be placed in world

### ISSUE THREAD

**Issue by JellyBlade** [modmuss50/SC2#42]
This is the issue I was facing previously on #40 (which relates to #23).

After "extensive" testing on my heavily-modded world, I figured out that my cart failing to be placed had something to do with solar panels. 
Upon creating another instance (this time, just running steve's carts 2 by itself with no other mods), I found that creating a cart containing a solar panel module (of any type, regular/basic/compact) and a woodcutting module (basic/reinforced/galgadorian) in a cart prevents the cart from being placed. You can place the cart if it contains one of these modules, and any other number of modules, but having both installed prevents it from working properly. Any other type of cart works perfectly, this issue is only present with a woodcutter and a solar panel.

http://pastebin.com/KAxrs0tx (fml log)
Sorry for bothering you again, but as this seems to be an issue with the steve's carts 2, and not a rogue mod interaction, I thought I might as well bring it to your attention.

**Comment by modmuss50** [comment]
Ok thanks, the last fix would have removed any possibly of it being another mod.

**Comment by modmuss50** [comment]
Ok, just put out another beta build that should hopefully fix it. Please report back to me if it helps.

**Comment by JellyBlade** [comment]
Yep, that fixed it, tried a bunch of cart combinations, just in case, and they all work. Building a new woodcutter cart on my heavily modded world with the new build works perfectly. Thank you! Infinite wood!

**Comment by modmuss50** [comment]
Nice! Thanks for your help with tracking this down.

**Comment by sintaxcz** [comment]
Hello i have this on my server too with latest 1.10.2 build :(  (StevesCarts-1.10.2-2.1.4.83.jar)
