### ISSUE TITLE
Assembled carts lack an icon

### ISSUE THREAD

**Issue by FnordMan** [modmuss50/SC2#5]
Attached picture. 
![aa](https://cloud.githubusercontent.com/assets/7041560/20220902/e9092eb4-a7f4-11e6-917e-0feb62e96860.png)

**Comment by modmuss50** [comment]
Humm, for me it renders the cart. Do you have mods like optifine and are you in single player or multiplayer?

**Comment by Garonne** [comment]
I'm playing singleplayer and have optifine running... No problems for me...

**Comment by modmuss50** [comment]
There might be another mod overriding our rendering. If needed I should be able to make a small mod to allow us to track it down.

**Comment by FnordMan** [comment]
No optifine or anything like that, this is purely single player for now. 
[modlist.txt](https://github.com/modmuss50/SC2/files/586329/modlist.txt)
/\ current modlist, just grabbed a quick directory dump of the mods folder.

**Comment by modmuss50** [comment]
Hum, ok I may make a quick mod to see If I can find out what is overriding the rendering "hook" im using

**Comment by modmuss50** [comment]
Could you try this version:

http://modmuss50.me:8080/job/StevesCarts/job/StevesCarts-1.10.2/16/artifact/build/libs/StevesCarts-1.10.2-2.1.0.16.jar

I've registered the Item Renderer as late as possible to try and do it after the broken mod. If its still an issue, I will add a item to the debug menu to try and track it down.

**Comment by modmuss50** [comment]
Im closing this, let me know if its still an issue, and I will look into it more.
