### ISSUE TITLE
Mystical Crops compatability

### ISSUE THREAD

**Issue by FnordMan** [modmuss50/SC2#6]
Relatively minor issue here: The farmer will harvest mystical crops just fine but you can't put the seeds in the farmer for planting.  The seeds and the essence end in whatever storage it's got.

**Comment by modmuss50** [comment]
That should be possible to do, I will need to see if we need to get an api to allow mods to add their own custom support.

**Comment by modmuss50** [comment]
We have `ICropModule` that can be used to add whole new modules to support different plants, for example netherwart's as seen in `ModuleNetherwart`. 

I think we should make a simple API to allow other mod devs to register their seed types with the default farmer without having to add a whole new module (impossible for another mod to do that atm).

**Comment by modmuss50** [comment]
I have sarted making a basic API to allow any mods to add their own plant and trees. When its done I will let you know.

I wont be able to add support for every mod, I should be able to cover the most popular ones though. If mod devs want to add their own support, they will be able to do so.

**Comment by modmuss50** [comment]
I have added an API, it should serve all the functions needed, I may improve the seed API soon, but I need something to test with. I do not see an api for `Mystical Crops` so I wont be able to easily add support for it.

Please either ask the mod author nicely to use our api, or send them my way. #StevesCarts on esper.net IRC is the best place for this. thanks

**Comment by modmuss50** [comment]
Ok, we work out of the box will all IPlantables I tested it with IPlantables.
