### ISSUE TITLE
Advanced Control System Unexpected Dismount

### ISSUE THREAD

**Issue by dannydjdk** [modmuss50/SC2#68]
Version: 2.1.4.83
Forge: 12.18.3.2297
Pack: FTB Beyond 1.8.1

Player dismounts from cart when pressing shift. Therefore, it is not possible to slow down cart.
Player also dismounts when right clicking the cart. Therefore it is not possible to access GUI while riding.
It also ignores attempts to change direction at junctions.
So, the only action you can perform with the advanced control system is to make the cart go and then dismount while it's moving.

**Comment by modmuss50** [comment]
Humm, I might have to change the control scheme a bit, as shift is used to dismount enitys in newer mc versions.

**Comment by dannydjdk** [comment]
I did discover that pressing "S" repeatedly does slow down the cart, so we can use that to work around the dismount on shift problem. But, not being able to access the GUI while riding is still a problem as is the inability to control the direction at junctions.
