### ISSUE TITLE
Wood cutter not planting

### ISSUE THREAD

**Issue by Ventrylock** [modmuss50/SC2#69]
I'm having an issue. I made a cart with :
- standard hull
- coal engine
- basic wood cutter
- storage front, side and internal
When I place it on rail he doesn't plant saplings. But he cut trees.
Does anyone have a solution ?

**Comment by Ventrylock** [comment]
Here you can find all the files I use in my mod pack.
https://www.dropbox.com/sh/39g9950dzslstyq/AAAbPY8f1hBXXYauFB1dja8Sa?dl=0

**Comment by thefrasca** [comment]
@Ventrylock I am not part of the team, but I noticed that sometimes you need to ensure that dirt is actually available 2 levels deep from the surface in order for the cart to plant.  So not only dirt where the tree should be planted, but dirt 1 block below that as well.

**Comment by modmuss50** [comment]
Ok, that might explain why I cannot get it to happen in my superflat worlds 👍

**Comment by Ventrylock** [comment]
Thx for reply.
Still not working.
What do you have when you assemble your carts ?

**Comment by Ventrylock** [comment]
Update the mod and it work now. Thx for try to help guys :)
