### ISSUE TITLE
Not compatiable with IC2Classic.

### ISSUE THREAD

**Issue by mindcloud69** [modmuss50/SC2#70]
Crashes when [IC2 Classic](https://minecraft.curseforge.com/projects/ic2-classic?gameCategorySlug=mc-mods&projectID=242942) is installed with StevesCarts-1.10.2-2.2.0.86.

[Crash Log](https://gist.github.com/mindcloud69/829e5ec5b7860b549b987dce9e141bd5)

**Comment by modmuss50** [comment]
I don't support ic2 classic. Use proper ic2

**Comment by mindcloud69** [comment]
Would you accept a PR fixing this as long as it was non breaking for IC2 EXP?

**Comment by modmuss50** [comment]
I guess so.
