### ISSUE TITLE
1.12 Crafting Issue

### ISSUE THREAD

**Issue by whatthedrunk** [modmuss50/SC2#71]
When installing on 1.12 it breaks crafting. If you try to make something like a Stone Pickace it's almost impossible. If you shift click 2 logs to make planks there is a ghost item that crashes you if you click it and if you try to make a stone pick things disappear and reappear it's pretty strange.  If you need any more info let me know.

**Comment by modmuss50** [comment]
Humm, are you using the latest forge and RC?

**Comment by modmuss50** [comment]
Ok, looked into it more. I think forge still has some bugs with the crafting system, and I know lex has some things unpushed that changes a lot. I think the best thing to do is for us to wait until forge updates. And then go from there.

**Comment by modmuss50** [comment]
Ok, it should be better now, there may still be some issues with recipes from SC. But it should fix the whole crafting table being broken.

Let me know if you find any issues.
