### ISSUE TITLE
Cargo Manager UI Bug

### ISSUE THREAD

**Issue by NoLiver92** [modmuss50/SC2#73]
- Minecraft: 1.12
- forge-1.12-14.21.1.2387
- StevesCarts-1.12-2.4.3.22
- RebornCore-1.12-3.2.1.77-universal
- More mods are installed

When the cargo manager UI is open and you click to change the colours of the boxes and the direction of flow, the colour of that box doest change, another box changes. Every icon on the UI doesnt do thats expected except for the top tight colour box. Also when you click the change direction button (next to change colour button and under the coloured square) the client just closes, quitting the game. It states fatal error and theres no crash report generated

**Comment by modmuss50** [comment]
Ok, I think I tracked it down. I have a dev build you can test with here: https://jenkins.modmuss50.me/job/Team%20Reborn/job/StevesCarts/job/1.12/

**Comment by NoLiver92** [comment]
Brilliant, its working as expected now. Thanks for your quick reply.
