### ISSUE TITLE
Unable to click on arrows or color changer in cart manager gui

### ISSUE THREAD

**Issue by TheElectricCake** [modmuss50/SC2#78]
Setting a cart manager block down next to an advanced detector rail, if I open the gui by right-clicking the block, I am able to manually move things in and out of the inventory, but if I click on any of the arrows to change the direction in which the cart manager will interact with carts, or if I click on any of the color-changer icons for any side of the cart manager block, it immediately crashes minecraft out of single-player or SMP.

**Comment by modmuss50** [comment]
I need the crash log.

**Comment by modmuss50** [comment]
Closing as no log was provided.
