### ISSUE TITLE
Advanced Smelter problem

### ISSUE THREAD

**Issue by JasonMcRay** [modmuss50/SC2#79]
So I was wondering why my Advanced Smelter does not work. After little bit of time, I have found out that it only smelts stuff that is in the Storage part of the Cart. The items to smelt are piling up in the Advanced Smelter module, but they are not getting consumed.

If I remember correctly it was smelting the items put in the Smelter itself and did not touched the storage...

**Comment by modmuss50** [comment]
Humm ok, I will take a look. Thanks

**Comment by GoryMoon** [comment]
Fixed
The slots are now fix how they should be, the slots are fake and you setup the recipe in them and then it smelts from the storage
