### ISSUE TITLE
Crash when inserting fluid into fluid manager with thermal dynamics fluiduct

### ISSUE THREAD

**Issue by Watchful1** [modmuss50/SC2#80]
https://pastebin.com/YpqLPPW3

Version 1.12-2.4.4.25. I haven't had a chance to try it with the newer version, but the changes mentioned didn't look relevant.

**Comment by modmuss50** [comment]
Thanks, I will take a look once I have a proper PC setup again.

**Comment by modmuss50** [comment]
![2017-07-23_17 02 18](https://user-images.githubusercontent.com/4324090/28500902-bf0fe02a-6fc8-11e7-93d4-f1aea3898498.png)
Took a lot more work than I had thought, but it seems to be working now. Just going to test it with a few other things and then I will push.
