### ISSUE TITLE
Cart Tanks

### ISSUE THREAD

**Issue by Moobien** [modmuss50/SC2#85]
Hey guys using version 1.11.2-2.3.0.22 and the cart tanks are completely nonfunctional.  I can put buckets into the input slot for the tank in the cart and the item just stays there.  please refer to the screenshots.  Also, the incinerator uses no lava (probably linked to the tank issue)

http://imgur.com/a/9uBxI

**Comment by Moobien** [comment]
No update on this?

**Comment by GoryMoon** [comment]
Fixed in the 1.12 version
