### ISSUE TITLE
Cart cannot be placed in the world

### ISSUE THREAD

**Issue by korol112** [modmuss50/SC2#89]
```
[00:26:19] [Server thread/ERROR] [stevescarts]:  --------------- Broken cart info ---------------
[00:26:20] [Server thread/INFO] [STDERR]: [vswe.stevescarts.items.ItemCarts:func_180614_a:61]: java.lang.ArrayIndexOutOfBoundsException
[00:26:20] [Server thread/ERROR] [stevescarts]:  --------------- Broken cart info ---------------
[00:26:20] [Server thread/ERROR] [stevescarts]: {Data2:100b,Modules:[11 bytes],CartVersion:2b}
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.hull.ModuleReinforced
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.engines.ModuleCoalStandard
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.workers.tools.ModuleDrillDiamond
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.workers.ModuleBridge
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.workers.ModuleRailer
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.storages.chests.ModuleTopChest
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.storages.chests.ModuleInternalStorage
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.addons.ModuleOreTracker
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.addons.ModuleHeightControl
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.addons.ModuleChunkLoader
[00:26:20] [Server thread/ERROR] [stevescarts]: --- vswe.stevescarts.modules.addons.ModuleLiquidSensors
[00:26:20] [Server thread/ERROR] [stevescarts]:  --------------- Broken cart info ---------------

```
Version: `STEVESCARTS-1.10.2-2.2.0.86.jar`

Placing a cart with the following properties fails: 

- Reinforced Hull
- Coal Engine
- Basic Drill
- Bridge Builder
- Railer
- Top Chest
- Internal Storage
- Ore Extractor
- Height Controller
- Chunk Loader
- Liquid Sensors

**Comment by modmuss50** [comment]
Have you got foamfix installed? If so what version?

**Comment by korol112** [comment]
@modmuss50 `FOAMFIX-0.7.0-BETA2-ANARCHY.jar`

**Comment by korol112** [comment]
The whole modlist:

ACTUALLYADDITIONS-1.10.2-R105.jar
ADVANCED MACHINES-60.0.4.jar
ADVANCED SOLAR PANELS-4.0.4.jar
AKASHICTOME-1.0-5.jar
appliedenergistics2-rv4-alpha-11.jar
AUTOREGLIB-1.0-2.jar
BASE-1.10.2-1.4.0.jar
BAUBLES-1.10.2-1.3.11.jar
BBG-1.9.4-5.0.0.jar
BDLIB-1.12.4.24-MC1.10.2.jar
BEDBUGS-1.10.2-1.1.6.jar
BIOMESOPLENTY-1.10.2-5.0.0.2236-UNIVERSAL.jar
BLOODMAGIC-1.10.2-2.1.11-80.jar
BOTANIA R1.9-340.jar
BRANDONSCORE-1.10.2-2.1.9.113-UNIVERSAL.jar
CHAMELEON-1.10.2-2.3.0.jar
CHICKENCHUNKS-1.10.2-2.2.0.52-UNIVERSAL.jar
CHISEL-MC1.10.2-0.0.13.29.jar
CHISELSANDBITS-12.14.jar
CLIENTTWEAKS_1.10.2-1.1.16.jar
CLUMPS-1.0.5.jar
CODECHICKENCORE-1.10.2-2.4.1.102-UNIVERSAL.jar
CODECHICKENLIB-1.10.2-2.5.9.283-UNIVERSAL.jar
COFHCORE-1.10.2-4.1.10.15-UNIVERSAL.jar
COMPATLAYER-1.10-0.2.9.jar
CONTROLLING-1.0.5.jar
COOKINGFORBLOCKHEADS_1.10.2-4.2.45.jar
COVERS-0.4.1.17-MC1.10.2.jar
CRAFTTWEAKER-1.10.2-3.0.26.jar
CTM-MC1.10.2-0.2.0.19.jar
CUSTOMMAINMENU-MC1.10.2-2.0.5.jar
DRACONIC-EVOLUTION-1.10.2-2.1.2.245-UNIVERSAL.jar
DRAWERSBITS-1.10.2-0.36.jar
ELECCORE-1.10.2-1.7.425.jar
EMBERS-0.104.jar
ENDERCOMPASS-1.9.X-1.2.3.2.jar
ENDERCORE-1.10.2-0.4.1.66-BETA.jar
ENDERIO-1.10.2-3.1.193.jar
ENDERTANKS-1.10.0-1.4.13.jar
ENDERZOO-1.10-1.2.3.44.jar
EXCHANGEORB-1.10.2-1.2.jar
EXTRAUTILS2-1.10.2-1.5.jar
FASTLEAVEDECAY-MC1.10.2-1.2.3.jar
FOAMFIX-0.7.0-BETA2-ANARCHY.jar
FORESTRY_1.10.2-5.2.17.379.jar
FORGELIN-1.5.0.jar
ForgeMultipart-1.10.2-2.0.0.38-universal.jar
FTBLIB-1.1X-3.6.5.jar
FTBTWEAKS-2.0.0.jar
FTBUTILITIES-1.1X-3.6.5.jar
GENDUSTRY-1.6.5.30-MC1.10.2.jar
GraveStone Mod 1.5.12.jar
GRAVITATION SUITE-3.0.1.jar
GUIDE-API-1.10.2-2.0.3-46.jar
IMMERSIVEENGINEERING-0.10-61.jar
IMMERSIVEPETROLEUM-1.10.2-1.0.7.jar
immersivetech-1.10.2-1.1.jar
INDUSTRIALCRAFT-2-2.6.245-EX110.jar
INVENTORYTWEAKS-1.61-58.jar
IRONBACKPACKS-1.10.2-2.2.27.jar
ironchest-1.10.2-7.0.15.804.jar
JEI_1.10.2-3.14.7.420.jar
JEIBEES-0.9.0.5-MC1.10.2.jar
JOURNEYMAP-1.10.2-5.4.7.jar
JUSTENOUGHBUTTONS-1.10.2-1.7.3.jar
JUSTENOUGHRESOURCES-1.10.2-0.5.9.3.jar
LIBRARIANLIB-1.10.1.jar
LIBVULPES-1.10.2-0.2.5-UNIVERSAL.jar
LIMELIB-1.10.2-1.5.4.jar
LLOVERLAYRELOADED-1.1.0-MC[1.9-1.10.2].jar
LUNATRIUSCORE-1.10.2-1.1.2.38-UNIVERSAL.jar
MALISISBLOCKS-1.10.2-4.2.0.jar
MALISISCORE-1.10.2-4.4.0.jar
MALISISDOORS-1.10.2-5.2.0.jar
MANTLE-1.10.2-1.1.5.jar
MCJTYLIB-1.1X-2.4.3.jar
MCMULTIPART-1.4.0-UNIVERSAL.jar
MDECORE-1.10.2-1.5.1.jar
MINEMENU-1.10.2-1.4.5-UNIVERSAL.jar
MODNAMETOOLTIP_1.10.2-1.6.0.jar
MODTWEAKER2-2.0.13.jar
MOREBEES-1.10.2-1.4.1.1.jar
Morpheus-1.10.2-3.1.13.jar
MORPH-O-TOOL-1.0-12.jar
MPBASIC-1.10.2-1.1.5.jar
MPUTILS-1.10.2-1.2.9.jar
MrTJPCore-1.10.2-2.0.1.20-universal.jar
MTLIB-1.0.3.jar
MULTISTORAGE-1.10.0-1.2.18B.jar
NATURALPLEDGE-R1.11.jar
NETHERCORE-1.10.2-2.0.3.jar
NETHERPORTALFIX_1.10.2-3.3.4.jar
NOTENOUGHWANDS-1.1X-1.5.5.jar
OMLIB-1.10.2-3.0.0-114.jar
OPENGLIDER-1.10.2-1.0.0.jar
OPTIONSYNC-1.10.2-R1.jar
P455W0RDSLIB-1.10.2-1.0.13.jar
PAMS HARVESTCRAFT 1.10.2J.jar
PLATFORMS-1.10.0-1.2.10.jar
plustic-5.2.1.2.jar
PRESSURE-1.3.1.25-MC1.10.2.jar
ProjectE-1.10.2-PE1.3.1.jar
ProjectRed-1.10.2-4.8.4.49-Base.jar
ProjectRed-1.10.2-4.8.4.49-fabrication.jar
ProjectRed-1.10.2-4.8.4.49-integration.jar
ProjectRed-1.10.2-4.8.4.49-lighting.jar
ProjectRed-1.10.2-4.8.4.49-mechanical.jar
ProjectRed-1.10.2-4.8.4.49-world.jar
PSIONICUPGRADES-R1.15.jar
PSI-R1.0-42.jar
QUANTUMSTORAGE-1.10.2-3.3.4.jar
QUARK-R1.1-68.jar
RAILCRAFT_1.10.2-10.1.2.jar
RANDOMTHINGS-MC1.10.2-3.7.7.1.jar
REBORNCORE-1.10.2-2.13.6.142-UNIVERSAL.jar
REDSTONEARSENAL-1.10.2-2.1.2.7-UNIVERSAL.jar
RESOURCELOADER-MC1.9.4-1.5.1.jar
RFTOOLS-1.1X-6.10.jar
RFTOOLSCTRL-1.1X-1.6.8.jar
RFTOOLSDIM-1.1X-5.02.jar
ROGUELIKEDUNGEONS-1.10.2-1.5.9.jar
ROUTERREBORN-1.10.2-4.0.1.88_UNIVERSAL.jar
ROUTERREBORNLIB-1.10.2-0.0.2.113.jar
SHETIPHIANCORE-1.10.0-3.3.9.jar
SIMPLEDIMENSIONS-MC1.10-1.3.jar
SIMPLYJETPACKS2-1.10.2-2.1.3.55.jar
STACKIE-1.10.2-1.6.0.44-UNIVERSAL.jar
STEVESCARTS-1.10.2-2.2.0.86.jar
STORAGEDRAWERS-1.10.2-3.7.10.jar
STORAGEDRAWERSEXTRAS-1.10-1.1.0.jar
SuperCircuitMaker-1.0.4.jar
SUPERCRAFTINGFRAME-1.10.2-1.2.1.88.jar
TCONSTRUCT-1.10.2-2.6.5.jar
TELEPACKS-1.10.2-1.0.jar
TESLA-1.10.2-1.2.1.49.jar
theoneprobe-1.1x-1.4.7.jar
THERMALDYNAMICS-1.10.2-2.0.9.15-UNIVERSAL.jar
THERMALEXPANSION-1.10.2-5.1.8.19-UNIVERSAL.jar
THERMALFOUNDATION-1.10.2-2.1.4.11-UNIVERSAL.jar
TINKER_IO-1.10.2-RELEASE 2.4.4.jar
TINKERTOOLLEVELING-1.10.2-1.0.1.jar
topaddons-1.10.2-0.14.1.jar
UNIDICT-1.10.2-2.9B.jar
VALKYRIELIB-1.10.2-0.10.6.jar
WANIONLIB-1.10.2-1.3.jar
XNET-1.3.2.jar
ZEROCORE-1.10.2-0.1.0.6.jar

**Comment by modmuss50** [comment]
Can you try disabling `fasterEntityDataManager` in the foamfix config? Also your foamfix version is very old, I would recommend updating it.

**Comment by korol112** [comment]
Updating foamfix to 0.7.2-anarchy seems to have fixed the issue.
