### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Goht** [modmuss50/SC2#91]
I think it would be nice to craft standard hull out of existing minecarts by slapping on iron wheels. Would make transitioning to the mod a bit kinder.

I also found that when I broke the Cart assembler, any items left in it disappeared, rather than either being kept in or being dropped like breaking a chest.

**Comment by modmuss50** [comment]
What feature? You didnt say what you wanted?

**Comment by Goht** [comment]
Also, my mistake about hitting enter too early. Had to go back in and edit my actual request, lol

**Comment by Goht** [comment]
Ah, while I'm here, I've also noticed that while the game tells me that it's adding recipes for Steve's Carts items, none of them are making it into my recipes book, while Tinker's Construct blocks are. Not sure if bug or somehow threw off the proper line of progression.

**Comment by modmuss50** [comment]
Yeah, I need to get around to adding the recipes to the book. Use JEI for now to see the recipes.

**Comment by Goht** [comment]
So, I hope you don't mind, but I just went ahead and downloaded JEI to look up the solar panel. Solar panels are showing up as Upgrade: Solar Panels. I'm not sure if they are acting as they should or if they are taking on different properties.

**Comment by Goht** [comment]
I really enjoy this mod, and I hope I'm not coming off as a complainer.

**Comment by modmuss50** [comment]
That item there is for putting onto the cart assembler, you want to use a solar engine to power the cart.

**Comment by Goht** [comment]
The Upgrade: Solar Panel is showing up to a requirement to create solar engines and the like. There is no basic solar panel. I don't know if its just adopting the wrong name and icon or what. But JEI is showing two items that come up as the Upgrade: Solar Panel, and no item that is simply a solar panel.
