### ISSUE TITLE
[1.11.2] Crash When Using Cart Assembler

### ISSUE THREAD

**Issue by Fently** [modmuss50/SC2#95]
As is said in title. Here is [Crash Report](https://pastebin.com/LEAAP6R9)
It crashes instantly when trying to use the cart assembler, unfortunately.

Minecraft v1.11.2
Forge v1.11.2-13.20.1.2476
StevesCarts v1.11.2-2.3.0.22
RebornCore v1.11.2-2.16.0.112

**Comment by modmuss50** [comment]
Not our bug, report to nei please.
